package billingModels

// Global variables

var MeterLookup priceMeter
var VmSizeLookup vmLookup
var ManagedDiskLookup managedDiskLookup
var PlatformMapLookup platformMapLookup
var ReportingCategoryLookup reportingCategoryLookup
var SummaryCategoryLookup summaryCategoryLookup
